# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55e0e7f7bf0aa388fcc590f19b0aa39af10c56442c143c7561ab1221073c7262d53f34a804815ad99275a52a6b0378dda4707acb3981c4fefacfe53bab537bf

test:
  secret_key_base: 849ceced8d833d041ca66a2dc1182fa1fcad738cc9312ff1c243f8e888cb95d59480f2ae4a3c97998bf7f3c1fdfb00647da401e415046e7152fa50fcb16258f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
